import { NextAuthOptions } from "next-auth";
import CredentialsProvider from "next-auth/providers/credentials";
import bcrypt from "bcryptjs"
import dbConnect from "@/lib/dbConnect";
import UserModel from "@/model/User.model";

export const authOptions: NextAuthOptions = {
    providers: [
        CredentialsProvider({
            id: "credentials",
            name: "Credentials",
            credentials: {
                email: { label: "Email", type: "text" },
                password: { label: "Password", type: "password" },
            },
            async authorize(credentials: any): Promise<any> {
                await dbConnect()
                try {
                    const user = await UserModel.findOne({
                        $or: [
                            { email: credentials.identifier },
                            { username: credentials.identifier }
                        ]
                    })
                    if (!user) {
                        throw new Error("No user found with this email or username")
                    }
                    if (!user.isVerified) {
                        throw new Error("Please verify your email first")
                    }
                    const isPasswordCorrect = await bcrypt.compare(credentials.password, user.password)

                    if (isPasswordCorrect) {
                        return user
                    }
                    else {
                        throw new Error("Incorrect password")
                    }
                } catch (error: any) {
                    throw new Error(error)

                }
            }
        })
    ],
    callbacks: {
        async jwt({ token, user }) {
            //next-auth token gives us limited information so for adding more items we need to modify the existing type of user returned by next-auth. And we do that in special file in types in next-auth.d.ts
            if (user) {
                token._id = user._id?.toString()  //this _id is id generated by mongodb for its each documents
                token.isVerified = user.isVerified
            }
            return token
        },
        async session({ session, token }) {
            return session
        }
    },
    pages: {
        signIn: "/signin",
    },
    session: {
        strategy: "jwt"
    },
    secret: process.env.NEXTAUTH_SECRET
}